### ISSUE TITLE
Memcached seems to be empty

### ISSUE THREAD

**Issue by agougousis** [fastogt/fastonosql#7]
I have achieved to connect to my memcached server but there seems to be no contents. My PHP code uses a key-value pair from the memcached so this pair has to appear on the FastoNoSql interface, shouldn't it?

**Comment by topilski** [comment]
Good day, yes in FastoNoSQL you should see full content of your memcached server.

**Comment by agougousis** [comment]
Ohh, now it can't even connect! Logs says:  "Connect to server error: SOME ERRORS WERE REPORTED".
My PHP code still uses the memcached without a problem!

**Comment by topilski** [comment]
You use localserver or remote?

**Comment by agougousis** [comment]
Remote.

**Comment by topilski** [comment]
FastoNoSQL on which platform? Sasl connection?

**Comment by agougousis** [comment]
Memcached on Linux (Ubuntu) and FasttoNoSQL on Windows 7.

**Comment by agougousis** [comment]
Ok, somehow the connection lost the IP and was reset to localhost. Now, it connects.
When I try to get the contents, it says: "Not supported command: KEYS"

**Comment by topilski** [comment]
Please attach FastoNoSQL log file which you can find in your home directory.

**Comment by topilski** [comment]
"Not supported command: KEYS" it means that FastoNoSQL can't retrive your db keys, because i don't know how to do this via Memcached api.

**Comment by agougousis** [comment]
So, how on earth the keys (displayed in the site screenshot of memcached feature) have been retrieved? :-(

**Comment by topilski** [comment]
Please specify the screenshot link location, we will remove it.

**Comment by topilski** [comment]
Keys can apear in memcashed DB tree if you create key via "Create key dialog" and should displayed on in this FastoNoSQL session, because we added keys into the tree. But when you reload application this keys didn't displayed, because we didn't fid solution how to retrive keys from Memcached, but keys which you create in previous sessions or other ways will be exists. Sorry for this, but we didn't find how to get keys from Memcached DB.

**Comment by agougousis** [comment]
Hmm! I think it is a matter of misunderstanding. Indeed, I can see many pages mentioning that Memcached doesn't provide a way to retrieve the cached keys. So, displaying the contents of Memcached is impossible, except if you already know the keys...or not! Listing slabs and then listing the keys of each slab IS POSSIBLE. It is described here: 
 http://www.alphadevx.com/a/90-Accessing-Memcached-from-the-command-line 
I have tried it and it works! Am I missing something?

**Comment by topilski** [comment]
Hello @agougousis , thank you for useful link i implemented "KEYS" command for memcached. If you want i can send you binary file to your email early than official release will be.

**Comment by agougousis** [comment]
Take your time! I am not in a hurry. Anyway, it will be a very useful feature!

**Comment by topilski** [comment]
Good day @agougousis , we released new version of FastoNoSQL please update your version and check  status of this issue.

**Comment by agougousis** [comment]
Hi there! Sorry, I am little busy today. I will check it out tomorrow.

**Comment by agougousis** [comment]
I am not sure that it works fine. 

![screen1](https://cloud.githubusercontent.com/assets/5471589/17587296/0ec9bd3e-5fd0-11e6-8f00-9b8e02462d18.png)

![screen2](https://cloud.githubusercontent.com/assets/5471589/17587301/12639c3a-5fd0-11e6-8a92-3e310d7737f4.png)

The number of keys (displayed in red letters) in the database is right. The first time I load the contents there is only 1 key (with name "laravel:key1") and the second time there is no key in the database. The other 2 keys displayed below are coming from outer space! :-) Maybe remains of connections made with the previous installation? No matter if there are keys in the database, the contents displayed below the database icon (below the red letters) remain the same and wrong!

**Comment by topilski** [comment]
Hi @agougousis, please update your version of FastoNoSQL, i think i have fixed this issue.

**Comment by topilski** [comment]
ping

**Comment by agougousis** [comment]
That was a useful ping! :-) Sorry for the long silence. I will give a try the new version in a few days cause I am leaving for a short trip tomorrow.

**Comment by agougousis** [comment]
Hi! I am still getting the same results. 
![ss](https://cloud.githubusercontent.com/assets/5471589/20261035/bed5597a-aa64-11e6-9772-996f98c450a4.png)
There are 3 items in cache, the ones with "gtis_mine" prefix. The other ones have been expired. The "stats items" command verifies that.
![stats](https://cloud.githubusercontent.com/assets/5471589/20261079/01510e52-aa65-11e6-812f-3195b09c65da.png)

**Comment by topilski** [comment]
Hi @agougousis , i implemented routine in 1.2.0 version which can handle expired keys for memcached please try new release, waiting for your feedback thx!

**Comment by topilski** [comment]
ping

**Comment by agougousis** [comment]
Hi! Sorry for the late response.
I think there is some progress but: 

Keys that have been removed from memcached need to be cleared manually from FastoNoSQL. Of course, by reloading the database (even if I dis/connect first) the second number changes to reflect the number of "new" keys (e.g from (5/5) to (5/3) ). I don't know if this happens intentionally but, if it is, you'd better highlight in someway the ones that are old. Whatever, in a case of (200/40) it gets a mess.

Connection settings are lost when restarting the application.

**Comment by agougousis** [comment]
Of course, the original issue has been technically solved, so maybe you can close this and open separate issues for these 2 things that I mentioned. Or not! :-)

**Comment by topilski** [comment]
Hi @agougousis, thank you for response we can write here it is normally.
